name: Tag and Release

on:
  pull_request:
    types: [closed]

jobs:
  tag-and-release:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'automated-pr')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract latest version from CHANGELOG.md
        id: extract_version
        run: |
          VERSION=$(awk '/## Unreleased/{getline; getline; print}' CHANGELOG.md | grep -oP '\[\K[0-9]+\.[0-9]+\.[0-9]+(?=\])')
          echo "Latest version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Tag Merge Commit
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag -a "${{ steps.extract_version.outputs.version }}" -m "Tagging release ${{ steps.extract_version.outputs.version }}"
          git push origin --tags

      # extract the content between the second and third H2 headers
      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1

      # creates an official release with the tagged version and release notes from above step
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: ${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false
          body: ${{ steps.extract_release_notes.outputs.release_notes }}